import Foundation

struct RunState {
    // MARK: - Run structure (Acts v1)
    static let actCount: Int = 3
    static let floorsPerAct: Int = 10 // normal floors before boss

    // MARK: - Run persistence (v1)
    var playerMaxHP: Int
    var playerHP: Int

    /// Card upgrade levels persisted for the whole run.
    /// Default is 1 for any card kind not present in the dictionary.
    var cardLevels: [ActionCardKind: Int]
    
    /// Run deck: all cards in the current run with their individual levels
    var runDeck: [ActionCard]

    /// 1...actCount
    var actIndex: Int

    /// 1...floorsPerAct for normal floors, floorsPerAct+1 for boss floor
    var floorInAct: Int

    var nonCombatStreak: Int
    
    /// Legacy room options - kept for backward compatibility
    /// When towerMap is present, this is computed from reachable nodes
    var roomOptions: [RoomOption]
    
    // MARK: - Tower Map (new branching system)
    
    /// The current act's map with branching paths
    var towerMap: TowerMap?

    /// Becomes `true` after the 3rd boss is defeated.
    var isCompleted: Bool = false

    // MARK: - Derived
    var isBossFloor: Bool {
        floorInAct == Self.floorsPerAct + 1
    }

    /// 1...33 (3 acts × (10 + boss))
    var globalFloor: Int {
        let floorsPerActIncludingBoss = Self.floorsPerAct + 1
        return max(1, (actIndex - 1) * floorsPerActIncludingBoss + floorInAct)
    }

    var globalFloorsTotal: Int {
        Self.actCount * (Self.floorsPerAct + 1)
    }

    var floorsRemainingToBoss: Int {
        max(0, Self.floorsPerAct + 1 - floorInAct)
    }
    
    /// Returns true if the player hasn't selected their first room yet
    var isAtMapStart: Bool {
        towerMap?.currentNodeId == nil
    }
    
    /// Get available room choices from the tower map
    /// Falls back to legacy roomOptions if no map
    var availableRooms: [RoomOption] {
        if let map = towerMap {
            return map.reachableRoomOptions()
        }
        return roomOptions
    }

    mutating func advanceAfterClearingCurrentFloor() {
        guard !isCompleted else { return }

        if isBossFloor {
            if actIndex >= Self.actCount {
                isCompleted = true
                return
            }
            actIndex += 1
            floorInAct = 1
            // Note: towerMap will be regenerated by GameStore for new act
            towerMap = nil
            return
        }

        floorInAct = min(Self.floorsPerAct + 1, floorInAct + 1)
    }
    
    // MARK: - Tower Map Navigation
    
    /// Move to a specific node on the map
    /// Returns the room option if successful
    @discardableResult
    mutating func moveToMapNode(nodeId: UUID) -> RoomOption? {
        guard var map = towerMap else { return nil }
        
        if map.moveTo(nodeId: nodeId) {
            towerMap = map
            return map.node(withId: nodeId)?.room
        }
        return nil
    }
    
    /// Mark current map node as completed
    mutating func completeCurrentMapNode() {
        towerMap?.completeCurrentNode()
    }
    
    /// Check if a room is reachable via the map
    func isRoomReachable(_ room: RoomOption) -> Bool {
        guard let map = towerMap else {
            // Legacy mode: all roomOptions are reachable
            return roomOptions.contains(where: { $0.id == room.id })
        }
        
        // Find node with this room
        return map.reachableNodes().contains(where: { $0.room.id == room.id })
    }
    
    /// Get the node ID for a given room option
    func nodeIdForRoom(_ room: RoomOption) -> UUID? {
        guard let map = towerMap else { return nil }
        return map.allNodes.first(where: { $0.room.id == room.id })?.id
    }

    /// Start of a run: Act 1, Floor 1.
    init() {
        self.playerMaxHP = 20
        self.playerHP = 20
        self.cardLevels = [:]
        self.actIndex = 1
        self.floorInAct = 1
        self.nonCombatStreak = 0
        self.roomOptions = []
        self.towerMap = nil
        self.runDeck = []
    }
}
